- LICENSE
> add missing LICENSE file

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
- deploy/crds/syn.tools_gitrepos_crd.yaml
- pkg/apis/syn/v1alpha1/gitrepo_types.go
- pkg/controller/gitrepo/gitrepo_reconcile.go
- pkg/controller/gitrepo/gitrepo_reconcile_test.go
Update both the object with it's labels and the status. Set the status
to "created" if no errors occured.
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
> Update GitRepo objects properly

- CHANGELOG.md
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
> Prepare release v0.1.1

- CHANGELOG.md
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
> Prepare release v0.1.4

- README.md
- deploy/crds/kustomization.yaml
- deploy/deployment.yaml
- deploy/kustomization.yaml
- deploy/role.yaml
- docs/modules/ROOT/pages/gettingstarted.adoc
To make deployments easier.
Signed-off-by: Simon Rüegg <simon@rueggs.ch>
> Create Kustomize setup

- CHANGELOG.md
- deploy/kustomization.yaml
Waits for https://github.com/projectsyn/lieutenant-operator/pull/88
> Prepare release v0.2.0

- docs/modules/ROOT/pages/explanation/design.adoc
> Add a diagram for Operator Design

- .yamllint.yml
- CHANGELOG.md
- docs/modules/ROOT/pages/references/configuration.adoc
- pkg/vault/client.go
- pkg/vault/client_test.go
To migrate to the new Vault setup: https://ticket.vshn.net/browse/SYN-196
> Make Vault secret engine path configurable

- CHANGELOG.md
- deploy/kustomization.yaml
> Fix deploy tag

- CHANGELOG.md
- deploy/kustomization.yaml
> Prepare release v0.3.0

- CHANGELOG.md
- deploy/kustomization.yaml
> Update CHANGELOG for release v0.4.0

- CHANGELOG.md
- pkg/controller/cluster/cluster_reconcile.go
- pkg/controller/tenant/tenant_reconcile_test.go
- pkg/pipeline/tenant_steps.go
- pkg/pipeline/tenant_steps_test.go
> Fix tenant common class import

- CHANGELOG.md
- pkg/controller/cluster/cluster_reconcile_test.go
- pkg/pipeline/git.go
Otherwise the URL will be overwritten with an empty string.
> Don't set git repo URL for unmanaged repos

- CHANGELOG.md
- pkg/pipeline/common_steps.go
- pkg/pipeline/common_steps_test.go
- pkg/pipeline/git.go
> Fix status update of objects

- CHANGELOG.md
- deploy/kustomization.yaml
> Prepare release v0.4.1

- CHANGELOG.md
- deploy/kustomization.yaml
> Prepare release v0.4.2

- CHANGELOG.md
- docs/modules/ROOT/pages/explanations/rbac-access.adoc
- docs/modules/ROOT/partials/nav-explanation.adoc
- go.mod
- pkg/controller/cluster/cluster_reconcile.go
- pkg/controller/cluster/cluster_reconcile_test.go
- pkg/controller/cluster/cluster_steps.go
- pkg/controller/gitrepo/gitrepo_reconcile.go
- pkg/controller/tenant/tenant_rbac.go
- pkg/controller/tenant/tenant_rbac_test.go
- pkg/controller/tenant/tenant_reconcile.go
- pkg/controller/tenant/tenant_reconcile_test.go
- pkg/controller/tenant/tenant_steps.go
- pkg/pipeline/pipeline.go
- pkg/role/role.go
- pkg/role/role_test.go
> Per tenant access to tenant and cluster objects

- CHANGELOG.md
- deploy/kustomization.yaml
> Prepare release v0.5.0

- CHANGELOG.md
- deploy/kustomization.yaml
> Update image tag to v0.5.1 and fix changelog

- CHANGELOG.md
- pkg/git/gitlab/gitlab.go
- pkg/git/gitlab/gitlab_test.go
See https://docs.gitlab.com/ce/api/README.html#pagination
> Iterate all pages in a repository file listing

- CHANGELOG.md
- deploy/kustomization.yaml
> Prepare release v0.5.2

- deploy/kustomization.yaml
> Prepare for v0.5.3

- Makefile
- Makefile.vars.mk
> Update K8s version to v1.21

- config/manager/manager.yaml
- e2e/definitions/operator/deployment.yaml
> Fix spelling of lieutenant

- vault/client.go
- vault/log_adapter.go
This PR allows to debug vault problems that could be hidden by the default noop logger.
> Log vault errors and messages

- vault/client.go
- vault/log_adapter.go
- vault/log_adapter_test.go
Log vault client logs instead of vaults http logs. Note the differing logging interfaces, lovely.
> Fix vault client logging

- pipeline/pipeline.go
- pipeline/steps.go
- pipeline/steps_test.go
> Steps and status update debug logs

- Makefile
- docs/modules/ROOT/pages/how-tos/local-env.adoc
- docs/modules/ROOT/partials/nav-howtos.adoc
- e2e/.gitignore
- e2e/kind.mk
> Add how-to on running the Operator locally

- controllers/cluster/rbac.go
- controllers/cluster/role.go
- controllers/cluster/tenant.go
- controllers/cluster_controller.go
- controllers/gitrepo/steps.go
- controllers/gitrepo/template.go
- controllers/gitrepo/utils.go
- controllers/gitrepo_controller.go
- controllers/tenant/git.go
- controllers/tenant/role.go
- controllers/tenant/role_binding.go
- controllers/tenant/service_account.go
- controllers/tenant/template.go
- controllers/tenant_controller.go
- git/manager/manager.go
- pipeline/pipeline.go
- pipeline/steps.go
- vault/reconcile_steps.go
Merge after https://github.com/projectsyn/lieutenant-operator/pull/201
> Remove all `context.TODO()`

- config/samples/deployment/deployment.yaml
- config/samples/deployment/kustomization.yaml
> Update sample deployment operator image tag

- controllers/cluster/template.go
- controllers/cluster/template_test.go
- docs/modules/ROOT/pages/explanations/templating.adoc
> Make Tenant available in the Cluster Template

- docs/Makefile
> Updated antora-preview image

- api/v1alpha1/gitrepo_types.go
- controllers/gitrepo/steps.go
- controllers/gitrepo/steps_test.go
> Stop adopting existing git repositories by default

- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/prometheus/kustomization.yaml
- config/prometheus/monitor.yaml
- config/rbac/auth_proxy_client_clusterrole.yaml
- config/rbac/auth_proxy_role.yaml
- config/rbac/auth_proxy_role_binding.yaml
- config/rbac/auth_proxy_service.yaml
- config/rbac/kustomization.yaml
- main.go
- metrics/compile_meta_collector.go
- metrics/compile_meta_collector_test.go
https://syn.tools/syn/SDDs/0031-component-version-tracking.html#_operator
> Collect Cluster compilation metadata metrics according to SDD 0031

- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/master.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> Cleanup CI

- config/samples/deployment/deployment.yaml
- config/samples/deployment/kustomization.yaml
Those image tags were forgotten before release usually,
> Examples: always point to latest image.

- metrics/cluster_info_collector.go
- metrics/cluster_info_collector_test.go
- metrics/tenant_info_collector.go
- metrics/tenant_info_collector_test.go
> Add Cluster and Tenant info metrics

- main.go
> Register new collectors

- controllers/cluster_controller.go
- controllers/gitrepo/utils.go
- controllers/gitrepo_controller.go
- controllers/tenant/git.go
- controllers/tenant_controller.go
- go.mod
- go.sum
- main.go
- pipeline/pipeline.go
- pipeline/steps.go
- pipeline/steps_test.go
- vault/reconcile_steps.go
- vault/reconcile_steps_test.go
> Disentangle random environment variables

- Makefile
> Update Makefile `run` target to include parameters needed for most local setups

- controllers/cluster_compile_pipeline_controller.go
- controllers/cluster_compile_pipeline_controller_test.go
- controllers/tenant_compile_pipeline_controller.go
- controllers/util.go
> Do not set CI variables as "protected"

- controllers/cluster_controller.go
Fixes changes to the cluster template not being picked up.
> Reconcile clusters on tenant change
