projectsyn/lieutenant-operator

go.mod, go.sum, pkg/controller/cluster/cluster_rbac.go, pkg/controller/cluster/cluster_reconcile.go, pkg/controller/cluster/cluster_reconcile_test.go
Create a ServiceAccount, Role and RoleBinding for new clusters to allow
steward to manage (get, update) it's own cluster object.
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
=> Implement RBAC handling for clusters

deploy/crds/syn.tools_clusters_crd.yaml, deploy/crds/syn.tools_gitrepos_crd.yaml, deploy/crds/syn.tools_tenants_crd.yaml, go.sum, pkg/apis/syn/v1alpha1/gitrepo_types.go, pkg/controller/gitrepo/gitrepo_reconcile.go, pkg/controller/gitrepo/gitrepo_reconcile_test.go, renovate.json
This value specifies if a GitRepo object is actually handled by the git
controller. A value of `unmanaged` means the controller won't manage it
and it's sole purpose is data storage. An empty value defaults to `auto`
which means it's managed by the controller.
Signed-off-by: Simon Rüegg <simon.ruegg@vshn.ch>
=> Implement GitRepo type

CHANGELOG.md, pkg/controller/cluster/cluster_reconcile.go, pkg/controller/tenant/tenant_reconcile.go, pkg/git/helpers/helpers.go, pkg/helpers/crd.go
This merge request fixes issues with:
* key comparison not working when using multiline strings in YAML
* gitrepourl not populated for tenants and clusters
=> Fix key compare with whitespaces and gitrepourl not populated

create-api-docs.sh, deploy/crds/syn.tools_clusters_crd.yaml, deploy/crds/syn.tools_gitrepos_crd.yaml, deploy/crds/syn.tools_tenants_crd.yaml, docs/modules/ROOT/pages/crds-html.adoc, docs/modules/ROOT/partials/crds.html, template/members.tpl, template/pkg.tpl, template/type.tpl
The html that gets generated with the default templates for the
`gen-crd-api-reference-docs` tool don't contain any classes in the
table tags. HTML classes are necessary to get the right look and feel
for our Antora sites. Because the HTML is simply pased through so we
have to handle the styling ourselves.
=> Adjust CRD doc templates

CHANGELOG.md, deploy/crds/syn.tools_clusters_crd.yaml, deploy/crds/syn.tools_gitrepos_crd.yaml, deploy/crds/syn.tools_tenants_crd.yaml, docs/modules/ROOT/partials/crds.html, examples/cluster.yaml, examples/gitrepo-secret.yaml, examples/gitrepo.yaml, examples/tenant.yaml, go.mod, go.sum, pkg/apis/syn/v1alpha1/gitrepo_types.go, pkg/apis/syn/v1alpha1/zz_generated.deepcopy.go, pkg/controller/cluster/cluster_reconcile.go, pkg/controller/cluster/cluster_reconcile_test.go, pkg/controller/gitrepo/gitrepo_reconcile.go, pkg/controller/gitrepo/gitrepo_reconcile_test.go, pkg/controller/tenant/tenant_reconcile.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_test.go, pkg/git/manager/manager.go
With this commit the GitRepo CRD was extended so it can hold a map of
file and content. Currently it's only tested to create files in the
root of a repository and not deeper in the file tree.
Also each cluster will now create an empty template file in its tenant
repository.
Relates to: #36
=> Implement git file templates

deploy/crds/syn.tools_clusters_crd.yaml, deploy/crds/syn.tools_gitrepos_crd.yaml, deploy/crds/syn.tools_tenants_crd.yaml, docs/modules/ROOT/partials/crds.html, pkg/apis/syn/v1alpha1/gitrepo_types.go, pkg/controller/cluster/cluster_reconcile.go, pkg/controller/cluster/cluster_reconcile_test.go, pkg/controller/gitrepo/gitrepo_reconcile.go, pkg/controller/gitrepo/gitrepo_reconcile_test.go, pkg/controller/tenant/tenant_reconcile.go, pkg/controller/tenant/tenant_reconcile_test.go, pkg/git/gitlab/gitlab.go, pkg/git/gitlab/gitlab_test.go, pkg/git/manager/manager.go
This Pull Request populates GitHub Repository `Description` field.
Here what has been changed:
* Whenever a cluster object is created/updated the `DisplayName` field will be passed as `Description` to GitHub Repository
* Whenever a tenant object is created/updated the `DisplayName` field will be passed as `Description` to GitHub Repository
* Whenever a gitrepo object is created/updated the `DisplayName` field will be passed as `Description` to GitHub Repository
* Added `Description` field management to `Create()` and `Update()` functions
* Added test cases for each modifications
=> Add git repository description

pkg/vault/client.go
Using `NewClientFromRawClient` does not initialize the client's own
logging. As it's not used when not in a k8s, this bug was only caught
when deployed to the first k8s cluster.
=> Fix nilpointer caused by the vault client

examples/cluster.yaml, examples/tenant.yaml, go.mod, go.sum, pkg/controller/gitrepo/gitrepo_reconcile.go, pkg/controller/gitrepo/gitrepo_reconcile_test.go, pkg/helpers/crd.go, pkg/helpers/crd_test.go
Updating the git repository every on every reconcile triggers a loop.
Not quite sure why it happens though, the diffs of the GitRepo objects
don't show any differences apart from `generation` and `resourceVersion`.
The operator will permanently reconcile all tenants and clusters as they
have the Gitrepository as their secondary objects. That triggers and
endless loop of reconciles.
Resolves: #54
=> Fix reconcile loop with GitRepo updates

pkg/controller/cluster/cluster_reconcile.go, pkg/controller/cluster/cluster_reconcile_test.go, pkg/controller/tenant/tenant_reconcile.go, pkg/controller/tenant/tenant_reconcile_test.go
Automatically set up a `common.yml` class in each tenant which is included by each cluster of a tenant.
Add option to disable Vault for local development.
=> Tenant Common

CHANGELOG.md, cmd/manager/main.go
This commit makes thes sync interval for the operator configurable. This
should reduce the load on any external components (git, vault, etc.).
=> Make operator sync interval configurable

CHANGELOG.md, pkg/controller/cluster/cluster_reconcile.go
If `SKIP_VAULT_SETUP` is set true and a deletion is triggered the Operator run into a nilpointer.
Resolves: #86
=> Fix nilpointer with VAULT client

Makefile
This PR provides upgrades antora-preview to the last version (2.3.4) which includes a new live reloading capability:
1. Run `make docs-serve`.
2. Open http://localhost:2020 on a browser with the [LiveReload plugin](https://github.com/vshn/antora-preview#livereload).
3. Edit your documentation in your preferred editor.
4. Watch your changes appear automatically on the browser.
=> Upgraded antora-preview to latest version

CHANGELOG.md, deploy/crds/syn.tools_clusters_crd.yaml, deploy/crds/syn.tools_tenants_crd.yaml, docs/modules/ROOT/pages/references/configuration.adoc, docs/modules/ROOT/partials/crds.html, pkg/apis/syn/v1alpha1/cluster_types.go, pkg/apis/syn/v1alpha1/tenant_types.go, pkg/controller/tenant/tenant_reconcile.go
https://github.com/projectsyn/commodore/issues/198 and https://github.com/projectsyn/commodore/issues/171 asks for a way to store git revisions. After discussing this with @simu  and @srueg, I opted to:
* Add a git URL for the global config repository to the tenant.
* Add revision fields for the global and the tenant config repos to both tenants and clusters.
For easier review, I have split the addition of the new fields and update of the generated resources into two separate commits.
=> Add configurable revisions for git repositories

pkg/pipeline/vault_test.go
We should only assert the vault client if it was actually used or else
it won't match the expected value.
With the use of a map instead of a slice the ordering isn't stable any-
more. There was a bug in the unit test that got triggered by that.
=> Fix error with Vault unit test

Dockerfile, Makefile
The released Docker images report their version as `<tag>-dirty`. This is due to how the version is determined during the docker build.
Since files like `Dockerfile` and `.dockerignore` are not copied into the container, `git` reports the tree status as "dirty".
This commit fixes this by injecting the actual version string from outside the build container.
=> Ensure released versions don't contain "-dirty"

CHANGELOG.md, pkg/apis/syn/v1alpha1/cluster_types.go, pkg/apis/syn/v1alpha1/gitrepo_types.go, pkg/apis/syn/v1alpha1/tenant_types.go, pkg/controller/cluster/cluster_reconcile.go, pkg/controller/gitrepo/gitrepo_reconcile.go, pkg/controller/tenant/tenant_reconcile.go, pkg/pipeline/cluster.go, pkg/pipeline/common.go, pkg/pipeline/common_steps.go, pkg/pipeline/common_steps_test.go, pkg/pipeline/pipelines.go, pkg/pipeline/reconcile_types.go, pkg/pipeline/tenant.go
The previous implementation caused the CRs to be updated with each
reconcile. Although no actual changes were applied the ResourceVersion
increased every time. This lead to the status not being set correctly.
And of course excessive reconciling.
By uptdating the status first and catching conflicts, we can avoid that.
This bug was only triggered for newly created GitRepos.
=> Avoid reconcile loop

.github/workflows/release.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
=> Remove usage of `::set-env` in GitHub Actions

CHANGELOG.md, deploy/role.yaml
Since #140, the operator needs more permissions for role and
rolebindings. This change adds them to the deployment file.
=> Grant more permissions on roles and rolebindings

pkg/controller/cluster/cluster_steps.go
Closes SYN-354 by increasing the default token validity to `1d`.
Also:
- Remove dead code
- Fix warning recarding capitalization of error message
=> Increase token validity

Makefile.vars.mk
The Docker image `projectsyn/lieutenant` was not able to be pushed to quay.io, because it should have been called `projectsyn/lieutenant-operator`. Interestingly, it was pushed to Docker Hub as https://hub.docker.com/r/projectsyn/lieutenant.
This should be cleaned up once this PR is merged.
=> Fix Docker image name in Makefile vars

Makefile.vars.mk, e2e/kind.mk, go.mod, go.sum, tools.go
Until now, the version of kind was managed via a variable in Makefile.vars.mk. This PR adds kind to the tools.go file and thereby the version is henceforth controlled via the go.mod file. This allows renovate to automatically update kind in the future. Kind will have to be started by go run sigs.k8s.io/kind instead of ./testbin/kind, yet manual invocation should not be necessary anyway.
See https://github.com/vshn/k8up/pull/468
=> Manage kind version via go.mod

controllers/gitrepo/steps.go
During refactor we seem to have lost the import that registered the Gitlab implementation.  This lead to all gitrepo reconciles to fail. This PR will add back this magic import.
I personally really don't like the magic `init` approach, as we have seen these imports can easily be missed when refactoring.
But I would say changing this is out of scope for this bugfix.
=> Register Gitlab implemenation

config/rbac/role.yaml, controllers/tenant_controller.go
This PR allows the `controller-manager` to `list`, `get` and `watch` TenantTemplates.
This fixes the log i've seen on lieutenant-dev:
```
E0809 15:10:15.392088       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.TenantTemplate: failed to list *v1alpha1.TenantTemplate: tenanttemplates.syn.tools is forbidden: User "system:serviceaccount:lieutenant-dev:lieutenant-dev-lieutenant-operator" cannot list resource "tenanttemplates" in API group "syn.tools" in the namespace "lieutenant-dev"
```
=> Allow `controller-manager` to `list`, `get`, and `watch` TenantTemplates

vault/client.go
The newBankVaultClient function returns a typed nil on error. This will cause subsequent calls to panic if we assign it directly to the global variable.
=> Fix typed nil assignment

vault/client.go, vault/client_test.go
Currently we panic during deletion if the cluster vault directory contains another directory. This is the case for example when following the [exoscale setup.](https://kb.vshn.ch/oc4/how-tos/exoscale/install.html#_set_secrets_in_vault)
This commit fixes this by recursively deleting all sub-directories. This should be the intended behavior of `removeSecret` anyway?
The one question I still have if deleting all secrets in the clusters directory is the intended behavior of `HandleVaultDeletion`
https://github.com/projectsyn/lieutenant-operator/blob/35c1bf7a5e6418e4db13c0aa4f5820399e8e2415/vault/reconcile_steps.go#L87-L100
At first sight this looks like it only deletes the `steward` secret, but it deletes all secrets of this cluster.
`bug`, `enhancement`, `documentation`, `change`, …
=> Adds recursive deletion of directories

git/gitlab/gitlab.go, git/gitlab/gitlab_test.go
We fix two bugs in this PR
* When creating (or recreating) a repository we will create a file containing `{delete}` for all deleted class files.
* When adding more than one file we try to create the last file multiple times because of a pointer error
=> Fix error when recreating git repository

api/v1alpha1/cluster_types.go, api/v1alpha1/gitrepo_types.go, api/v1alpha1/tenant_types.go, pipeline/pipeline.go, pipeline/steps.go
Update on the main resource does not update the status, but it does fetch the current version of that status from k8s. We currently use the orginal object in this update call, which has its status overwritten.  We need to copy the resource when updating to make sure that we can update both the resource and  its status.
=> Fix issue that blocked status updates

controllers/cluster_controller.go, controllers/gitrepo/utils.go, controllers/tenant_controller.go
There are currently two race conditions:
* Cluster / Tenant resources fetch the Git repo URL from the gitrepo resource but are not reconciled on its change
* Git repo resources fetch GitRepoTemplate from Cluster / Tenant but are not reconciled on their change.
closes #203
=> Fix git repository race condition

controllers/cluster/rbac.go
Last PR introduced a bug that removed the service account secret reference on reconcile. This caused kubernetes to recreate the SA token.
=> Fix recreated service account token bug

controllers/cluster/bootstrap_token.go, controllers/cluster/tenant.go, controllers/gitrepo/steps.go, controllers/gitrepo/utils.go, controllers/tenant/git.go, controllers/tenant/role.go, controllers/tenant/role_binding.go, controllers/tenant/service_account.go, controllers/tenant/template.go, pipeline/steps.go, vault/reconcile_steps.go
During troubleshooting issues with Lieutenant, we noticed that some
error messages did not contain enough information to find out which step
of a pipeline failed.
This commit tries to improve the errors reported back to the user by
making sure all errors returned in a `Result` contain some information
about the precise step that triggered it.
=> Add details about where errors occurred

config/rbac/role.yaml, controllers/cluster_controller.go, controllers/tenant/role.go, controllers/tenant/role_binding.go, controllers/tenant/service_account.go, controllers/tenant_controller.go
We add ServiceAccounts, Roles and Rolebindings as owned resources when setting up the tenant and cluster controllers. This ensures that a reconcile of the owning tenant or cluster is triggered if its associated ServiceAccount is deleted.
Additionally, we change the owner reference on the tenant ServiceAccount, Role and RoleBinding to be a controller reference so that the reconcile for a tenant is actually triggered when its ServiceAccount is deleted. Notably, reconciles aren't triggered for owned resources, if the owner reference isn't a controller reference (cf. documentation for [controllerutil.SetControllerReference] and [controllerutil.SetOwnerReference])
[controllerutil.SetControllerReference]: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#SetControll …
=> Reconcile Tenants and Clusters when their ServiceAccounts, Roles or Rolebindings change

git/gitlab/gitlab.go, git/gitlab/gitlab_test.go
The new version of the GitLab library URL-escapes the provided repo path in `GetNamespace`, so we must not escape it ourselves anymore, as we otherwise get a double-URL-escaped value for the request, which then fails.
Also add a test case for creating a project in a subgroup.
Follow-up fix for #217 
=> Remove unnecessary `url.PathEscape` for `GetNamespace`

git/gitlab/gitlab.go, git/gitlab/gitlab_test.go
The getter accesses the URL pointer, modifying the url stored in the Gitlab struct.
=> Prevent URL getter from modifying struct

api/v1alpha1/cluster_types.go, api/v1alpha1/gitrepo_types.go, api/v1alpha1/tenant_types.go, config/crd/bases/syn.tools_clusters.yaml, config/crd/bases/syn.tools_gitrepos.yaml, config/crd/bases/syn.tools_tenants.yaml, config/crd/bases/syn.tools_tenanttemplates.yaml, controllers/cluster_controller.go, controllers/gitrepo/steps.go, controllers/gitrepo/steps_test.go, controllers/gitrepo/utils.go, controllers/gitrepo_controller.go, controllers/tenant_controller.go, docs/modules/ROOT/pages/explanations/adoption.adoc, docs/modules/ROOT/pages/references/api-reference.adoc, docs/modules/ROOT/pages/references/configuration.adoc, main.go, pipeline/pipeline.go
This commit introduces a new field `CreationPolicy` for all managed resoruces. This field configures how Lieutenant handles the creation of Git repositories.
By default Lieutenant will not manage git repositories it did not create itself. This behaviour can be changed by setting the Creation Policy to `adopt`, which will allows Lieutenant to manage existing repositories. This can be helpful for migrations or recovery.
=> Make git repo creation behaviour configurable

config/crd/bases/syn.tools_clusters.yaml, config/crd/bases/syn.tools_gitrepos.yaml, config/crd/bases/syn.tools_tenants.yaml, config/crd/bases/syn.tools_tenanttemplates.yaml, generate.go
This is a leftover from pre-`v1` lieutenant. CRDs had the API version `v1beta1` which, when converted to `v1`, set `preserveUnknownFields=true`. Since the field was never explicitly managed it stayed `true` on clusters that had lieutenant `< v1` installed and was false on clusters that never used a `< v1` lieutenant.
The introduction of kubebuilder defaults with the upgrade of `k8s.io/api/core broke` old installations since defaults are not compatible with `preserveUnknownFields=true`.
This commit explicitly sets `preserveUnknownFields` to `false` in all CRDs.
Commit changing API version: https://github.com/projectsyn/lieutenant-operator/commit/8839a084ee005d084fe3f9ab7b814845f93bcc7d
Dependency upgrade: https://github.com/projectsyn/lieutenant-operator/commit/2d59a4c5882822ec7fd53bbfa57e2 …
=> Explicitly set `preserveUnknownFields` to `false`

controllers/cluster/rbac.go
Fixes Commodore CI compilation which uses `patch` for `compileMeta`.
=> Allow clusters to `update` and `patch` cluster status

controllers/tenant/role.go
Follow up of the cleanup in #272 .
=> Fix tenant without clusters allowed access to all clusters

config/manager/manager.yaml
Updating the image tag was often forgotten when releasing new versions.
=> Always point default deploy to latest image

controllers/gitrepo_controller.go, main.go
This helps to reconcile config drift and refresh expiring tokens even if the reconciler does not get triggered by cluster events.
=> Reconcile GitRepos every three hours

git/gitlab/gitlab.go, git/gitlab/gitlab_test.go
GitLab returns `404` on a `repository/tree` call if the repo has zero commits. We checked against the error message but the client library started to return a static `404` error which makes our check fail.
This commit changes the checking logic to check for the clients static `ErrNotFound` error. This might catch other errors too (repo does not exists at all), but those errors will be caught in the next step.
=> Fix initialization of GitLab repos

controllers/tenant_compile_pipeline_controller.go, controllers/tenant_compile_pipeline_controller_test.go
Replaces separator `,` by space (` `).
https://syn.tools/syn/SDDs/0032-compile-pipeline.html
=> Format `CLUSTERS` variable according to SDD.

controllers/cluster_compile_pipeline_controller.go, controllers/cluster_compile_pipeline_controller_test.go
=> Don't manage `ACCESS_TOKEN_` variables for unmanaged cluster git repos
